### ISSUE TITLE
Bug: Fix error in contribute.yearn.rocks

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-issues#17]
The filters are not working as intended or causing an error when you load the site, possibly due to overloading the github api.

**Comment by karelianpie** [comment]
@DarkGhost7 is this still a problem? I was able to open the site and it seems to be working as expected

**Comment by DarkGhost7** [comment]
> @DarkGhost7 is this still a problem? I was able to open the site and it seems to be working as expected

It's on the good first issue page. I still see it, yes.

**Comment by DarkGhost7** [comment]
@karelianpie

**Comment by karelianpie** [comment]
> It's on the good first issue page. I still see it, yes.

@DarkGhost7, I was able to find the root cause. The repo `yearn-data-analytics` was renamed `ydata` and for that reason we were getting a 404, also improved the way we handle the 404 errors as to not crash the whole page.

PR in review https://github.com/yearn/yearn-issues/pull/18

cc @Majorfi
